# Generated by Django 6.0.6 on 2026-06-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('id_document', models.CharField(max_length=50, verbose_name='Cédula/Pasaporte')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('room', 'Habitación'), ('gym', 'Gimnasio'), ('spa', 'Spa'), ('sauna', 'Sauna'), ('jacuzzi', 'Jacuzzi'), ('pool', 'Piscina'), ('event_room', 'Salón de Eventos'), ('conference', 'Sala de Conferencias'), ('restaurant', 'Restaurante')], max_length=20, verbose_name='Servicio')),
                ('check_in', models.DateField(verbose_name='Check-in')),
                ('check_out', models.DateField(verbose_name='Check-out')),
                ('adults_count', models.IntegerField(default=1, verbose_name='Adultos')),
                ('children_count', models.IntegerField(default=0, verbose_name='Niños')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('payment_uploaded', 'Comprobante Subido'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('special_requests', models.TextField(blank=True, verbose_name='Peticiones Especiales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.customer', verbose_name='Cliente')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('proof_image', models.ImageField(upload_to='payment_proofs/', verbose_name='Comprobante')),
                ('verification_status', models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado de Verificación')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Notas del Staff')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
