# Generated by Django 6.0.6 on 2026-06-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='584248304994', max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_link', models.URLField(default='https://api.whatsapp.com/send?phone=584248304994', verbose_name='Link WhatsApp')),
                ('instagram_username', models.CharField(default='dspahotel', max_length=100, verbose_name='Instagram')),
                ('instagram_link', models.URLField(default='https://www.instagram.com/dspahotel?igsh=ZjAwOHc0YXowZHBy', verbose_name='Link Instagram')),
                ('email', models.EmailField(default='Dspahotelreservaciones@gmail.com', max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(default='+58 424-8304994', max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(default='AV. Intercomunal, Lecheria, VE 6016', verbose_name='Dirección')),
                ('google_maps_embed', models.TextField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3921.5!2d-64.7!3d10.2!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTDCsDEyJzAwLjAiTiA2NMKwNDInMDAuMCJX!5e0!3m2!1ses!2sve!4v1234567890" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>', help_text='Pegar código iframe completo', verbose_name='Google Maps Embed')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="D'Spa Hotel", max_length=200)),
                ('mission', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('description', models.TextField(verbose_name='Descripción General')),
                ('objectives', models.TextField(help_text='Separar con punto y coma', verbose_name='Objetivos')),
                ('value_proposition', models.TextField(verbose_name='Propuesta de Valor')),
                ('competitive_advantages', models.TextField(help_text='Separar con punto y coma', verbose_name='Ventajas Competitivas')),
                ('values', models.TextField(help_text='Separar con punto y coma', verbose_name='Valores')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('facade_image', models.ImageField(blank=True, null=True, upload_to='facade/', verbose_name='Fachada')),
            ],
            options={
                'verbose_name': 'Información del Hotel',
                'verbose_name_plural': 'Información del Hotel',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('matrimonial', 'Habitación Deluxe Matrimonial'), ('double', 'Habitación Deluxe Doble')], max_length=20, verbose_name='Tipo')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('detailed_description', models.TextField(help_text='Incluir amenities y características', verbose_name='Descripción Detallada')),
                ('capacity_adults', models.IntegerField(default=2, verbose_name='Capacidad Adultos')),
                ('capacity_children', models.IntegerField(default=1, verbose_name='Capacidad Niños')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Noche')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('maintenance', 'Mantenimiento'), ('reserved', 'Reservada')], default='available', max_length=20, verbose_name='Estado')),
                ('has_terrace', models.BooleanField(default=True, verbose_name='Terraza')),
                ('has_safe', models.BooleanField(default=True, verbose_name='Caja Fuerte')),
                ('has_tv', models.BooleanField(default=True, verbose_name='TV')),
                ('has_closet', models.BooleanField(default=True, verbose_name='Closet')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Mini Nevera')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcón')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['room_type', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen')),
                ('icon_class', models.CharField(help_text='Ej: fas fa-spa', max_length=100, verbose_name='Clase de Icono')),
                ('category', models.CharField(choices=[('wellness', 'Bienestar'), ('corporate', 'Corporativo'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Imagen')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Imagen de Habitación',
                'verbose_name_plural': 'Imágenes de Habitaciones',
                'ordering': ['order'],
            },
        ),
    ]
