# Generated by Django 6.0.6 on 2026-06-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('can_verify_payments', models.BooleanField(default=False, verbose_name='Puede Verificar Pagos')),
                ('can_manage_reservations', models.BooleanField(default=False, verbose_name='Puede Gestionar Reservas')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Puede Ver Reportes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Staff',
                'verbose_name_plural': 'Perfiles de Staff',
            },
        ),
    ]
